file(READ ${IN} hex HEX)
string(LENGTH "${hex}" hex_length)
math(EXPR size "${hex_length} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
file(WRITE ${OUT} "extern const unsigned char ${SYMBOL}[] = {${bytes}};\nextern const unsigned long ${SYMBOL}_size = ${size};\n")
