name: macOS

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: SuperCollider's submodules
        run: git -C third_party/supercollider submodule update --init external_libraries/nova-simd external_libraries/nova-tt

      - uses: actions/cache@v4
        with:
          path: build-macos-deps
          key: macos-deps-${{ hashFiles('packaging/macos/build.sh') }}

      - name: Build
        run: packaging/macos/build.sh

      - uses: actions/upload-artifact@v4
        with:
          name: SuperColliDAW-macos
          path: build-macos/SuperColliDAW-macos.zip
